/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@InsightIntentEntity({
  entityCategory: 'artist entity category',
  parameters: {
    "$id": "/schemas/ArtistClassDef",
    "type": "object",
    "description": "Information about the artist",
    "properties": {
      "country": {
        "type": "string",
        "description": "The artist's country of origin",
        "default": "zh"
      },
      "city": {
        "type": "string",
        "description": "The artist's city of origin"
      },
      "name": {
        "type": "string",
        "description": "The name of the artist",
        "minLength": 1
      }
    },
    "required": ["name"]
  }
})
export class ArtistClassDef implements insightIntent.IntentEntity {
  entityId: string = "id";
  name: string = ''
}