/**
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function main() {}


interface I {
  get prop(): boolean
  set prop(prop: boolean)
  
}

class C implements I {
  public constructor() {}
  
  private _$property$_prop: boolean = true;
  public get prop(): boolean {
    return this._$property$_prop;
  }
  public set prop(_$property$_prop: boolean) {
    this._$property$_prop = _$property$_prop;
    return;
  }
  
}

