export const UT_PAGES: string[] = [
  // 'import/import@CustomDialog',
  // 'import/import@Observed',
  // 'import/importAllEts',
  // 'import/importEts',
  // 'import/importExportEts',
  // 'import/importExportNest',
  // 'import/importSystemApi',
  // 'import/importTs',

  // 'inner_commponent_transform/$$_component/$$_component',
  // 'inner_commponent_transform/custom_component/custom_component',
  // 'inner_commponent_transform/gesture_component/longPressGesture',
  // 'inner_commponent_transform/gesture_component/panGestrue',
  // 'inner_commponent_transform/gesture_component/pinchGesture',
  // 'inner_commponent_transform/gesture_component/rotationGesture',
  // 'inner_commponent_transform/gesture_component/swipeGesture',
  // 'inner_commponent_transform/gesture_component/tapGesture',
  // 'inner_commponent_transform/render_component/forEach/forEach',
  // 'inner_commponent_transform/render_component/forEach/forEachSecondFunction',
  // 'inner_commponent_transform/render_component/forEach/forEachTwo',
  // 'inner_commponent_transform/render_component/if/if',
  // 'inner_commponent_transform/render_component/lazyForEach/lazyForEach',
  // 'inner_commponent_transform/simple_component/button/button',
  // 'inner_commponent_transform/transition_component/animateTo/animateTo',
  // 'inner_commponent_transform/transition_component/pageTransition/pageTransition',

  // 'render_decorator/@builder/@builder',
  // 'render_decorator/@builder/@builderWithForEach',
  // 'render_decorator/@builder/@builderWithLinkData',
  // 'render_decorator/@builderParam/@builderParam',
  // 'render_decorator/@customDialog/@customDialog',
  // 'render_decorator/@extend/@extend',
  // 'render_decorator/@preview/@preview',
  // 'render_decorator/@styles/@styles',
  // 'render_decorator/@styles/@stylesExport',

  // 'ui_state_management/application_state_management/@storageLink/@storageLink',
  // 'ui_state_management/application_state_management/@storageProp/@storageProp',
  // 'ui_state_management/application_state_management/appStorage/appStorage',
  // 'ui_state_management/application_state_management/localStorage/localStorage',
  // 'ui_state_management/inner_struct_state_management/@link/@link',
  // 'ui_state_management/inner_struct_state_management/@prop/@prop',
  // 'ui_state_management/others/@consume_@provide/@consume_@provide',
  // 'ui_state_management/others/@observed_@objectLink/@observed_@objectLink',
  // 'ui_state_management/others/@watch/@watch'
];

export const UT_PARTIAL_UPFATE_PAGES: string[] = [
  // 'import/import@CustomDialog',
  // 'import/import@Observed',
  // 'import/importAllEts',
  // 'import/importEts',
  // 'import/importExportEts',
  // 'import/importExportNest',
  // 'import/importTs',

  // 'inner_component_transform/$$_component/$$_component',
  // 'inner_component_transform/$$_component/$$_componentCheck1',
  // 'inner_component_transform/$$_component/$$_componentCheck2',
  // 'inner_component_transform/$$_component/$$_componentCheck3',
  // 'inner_component_transform/$$_component/$$_componentCheck4',
  // 'inner_component_transform/$$_component/$$_componentCheck5',
  // 'inner_component_transform/$$_component/$$_componentCheck6',
  // 'inner_component_transform/$$_component/$$_componentCheck7',
  // 'inner_component_transform/$$_component/$$_componentCheck8',
  // 'inner_component_transform/$$_component/$$_componentCheck9',
  // 'inner_component_transform/$$_component/$$_if_elseIf_else',
  // 'inner_component_transform/custom_component/component_object',
  // 'inner_component_transform/custom_component/custom_component',
  // 'inner_component_transform/gesture_component/GestureModeParallel',
  // 'inner_component_transform/gesture_component/longPressGesture',
  // 'inner_component_transform/gesture_component/panGestrue',
  // 'inner_component_transform/gesture_component/pinchGesture',
  // 'inner_component_transform/gesture_component/rotationGesture',
  // 'inner_component_transform/gesture_component/swipeGesture',
  // 'inner_component_transform/gesture_component/tapGesture',
  // 'inner_component_transform/render_component/foreach/foreach',
  // 'inner_component_transform/render_component/foreach/forEachSecondFunction',
  // 'inner_component_transform/render_component/foreach/forEachThreeParam',
  // 'inner_component_transform/render_component/foreach/forEachTwo',
  // 'inner_component_transform/render_component/if/id_if',
  // 'inner_component_transform/render_component/if/if',
  // 'inner_component_transform/render_component/item/GridItem',
  // 'inner_component_transform/render_component/item/ListItem',
  // 'inner_component_transform/render_component/lazyforeach/lazyforeach',
  // 'inner_component_transform/render_component/lazyforeach/lazyforEachThreeParam',
  // 'inner_component_transform/render_component/repeat/repeat',
  'inner_component_transform/render_component/repeat/repeatAttr'
];

export const UT_VALIDATE_PAGES: string[] = [
  // 'Decorators/process_component_build/@BuilderParam',
  // 'Decorators/process_component_build/arkUIComponent',
  // 'Decorators/process_component_build/arkUIStandard',
  // 'Decorators/process_component_build/attributeCheck',
  // 'Decorators/process_component_build/buttonCheck',
  // 'Decorators/process_component_build/checkNonspecificParents',
  // 'Decorators/process_component_build/foreachParamCheck',
  // 'Decorators/process_component_build/idCheck', // Need to change error log
  // 'Decorators/process_component_build/ifComponent', // Miss one error message
  // 'Decorators/process_component_build/rootContainerCheck',
  // 'Decorators/process_component_build/stateStyles',

  // 'Decorators/process_component_class/@StylesParamChack',
  // 'Decorators/process_component_class/processComponentMethod',
  // 'Decorators/process_component_class/updateHeritageClauses',
  // 'Decorators/process_component_class/validateBuildMethodCount',
  // 'Decorators/process_component_class/validateDecorators',
  // 'Decorators/process_component_class/validateHasController',

  // 'Decorators/process_component_member/@linkInitialize',
  // 'Decorators/process_component_member/@objectLinkInitialize',
  // 'Decorators/process_component_member/processWatch',
  // 'Decorators/process_component_member/updateBuilderParamProperty',
  // 'Decorators/process_component_member/validateCustomDecorator',
  // 'Decorators/process_component_member/validateDuplicateDecorator', // Miss one error message
  // 'Decorators/process_component_member/validateForbiddenUseStateType',
  // 'Decorators/process_component_member/validateHasIllegalDecoratorInEntry',
  // 'Decorators/process_component_member/validateHasIllegalQuestionToken', // Miss one error message
  // 'Decorators/process_component_member/validateMultiDecorators',
  // 'Decorators/process_component_member/validateNonObservedClassType',
  // 'Decorators/process_component_member/validatePropertyDefaultValue',
  // 'Decorators/process_component_member/validatePropertyNonDefaultValue',
  // 'Decorators/process_component_member/validatePropertyNonType',
  // 'Decorators/process_component_member/validateWatchDecorator',
  // 'Decorators/process_component_member/validateWatchParam',

  // 'Decorators/process_custom_component/checkBuilder$$',
  // 'Decorators/process_custom_component/v2DecoratorInitFromParent',
  // 'Decorators/process_custom_component/validateForbiddenToInitViaParam',
  // 'Decorators/process_custom_component/validateIllegalInitFromParent',
  // 'Decorators/process_custom_component/validateInitDecorator',
  // 'Decorators/process_custom_component/validateMandatoryToInitViaParam',
  // 'Decorators/process_custom_component/validateNonLinkWithDollar',
  // 'Decorators/process_custom_component/validateParamTwoWayBind',

  // 'Decorators/process_import/index', // No such test case
  // 'Decorators/process_import/validateModuleName',

  // 'Decorators/process_struct_componentV2/param_require_once_check',
  // 'Decorators/process_struct_componentV2/v2Component_member_type_check',

  // 'Decorators/process_ui_syntax/EntryDecoParam',
  // 'Decorators/process_ui_syntax/ExtendOneChild',
  // 'Decorators/process_ui_syntax/NoSrc',
  // 'Decorators/process_ui_synta