/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Entry, Column, Component } from '@ohos.arkui.component'
import { StoragePropRef,State } from '@ohos.arkui.stateManagement'

@Entry
@Component
struct Parent {
  @State message: string = 'Hello';

  build() {
    Column() {
      // The '@StoragePropRef' property 'message' in the custom component 'Child' cannot be initialized here (forbidden to specify).
      Child({message: this.message});
    }
  }
}

@Component
struct Child {
  @StoragePropRef('111') message: string = 'Hello';
  build() {

  }
}