/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * THIS FILE IS AUTOGENERATED BY arktscgen. DO NOT EDIT MANUALLY!
 */

import {
    global,
    passNode,
    passNodeArray,
    unpackNonNullableNode,
    unpackNode,
    unpackNodeArray,
    assertValidPeer,
    AstNode,
    Es2pandaAstNodeType,
    KNativePointer,
    nodeByType,
    ArktsObject,
    unpackString
} from "../../reexport-for-generated"

export class Type extends ArktsObject {
    constructor(pointer: KNativePointer) {
        super(pointer)
    }
    get possiblyETSNullish(): boolean {
        return global.es2panda._TypePossiblyETSNullishConst(global.context, this.peer)
    }
    get definitelyETSNullish(): boolean {
        return global.es2panda._TypeDefinitelyETSNullishConst(global.context, this.peer)
    }
    get definitelyNotETSNullish(): boolean {
        return global.es2panda._TypeDefinitelyNotETSNullishConst(global.context, this.peer)
    }
    get clone(): Type | undefined {
        return new Type(global.es2panda._TypeClone(global.context, this.peer))
    }
    protected readonly brandType: undefined
}