/*
 * Copyright (c) 2024-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  $r,
  ResourceStr,
  SizeOptions,
  Length,
  ResourceColor,
  VoidCallback,
  Dimension,
  UIContext,
  Resource,
  Component,
  SymbolEffect,
  Builder,
  SymbolGlyph,
  SymbolEffectStrategy,
  Image,
  Row,
  ForEach,
  Button,
  BuilderParam,
  Scroller,
  Stack,
  Scroll,
  ScrollDirection,
  BarState,
  Alignment,
  BlendMode,
  BlendApplyType,
  HitTestMode,
  RowOptions,
  Padding,
  ButtonOptions,
  ButtonType,
  Color,
  Text,
  EffectComponent
} from '@ohos.arkui.component';

import {
  Consume,
  Link,
  Watch,
  ObjectLink,
  Observed,
  Require,
  State,
  Provide,
  PropRef,
  UIUtils
} from '@ohos.arkui.stateManagement';

import { SymbolGlyphModifier } from '@ohos.arkui.modifier';
import {
  AccessibilitySelectedType,
  Chip,
  ChipSize,
  ChipSuffixSymbolGlyphOptions,
  ChipSymbolGlyphOptions,
  CloseOptions,
  PrefixIconOptions,
  SuffixIconOptions,
  ChipOptions,
  LabelOptions
} from '@ohos.arkui.advanced.Chip';
import resourceManager from '@ohos.resourceManager';
import hilog from '@ohos.hilog';
import uiMaterial from '@ohos.arkui.uiMaterial';
import deviceInfo from '@ohos.deviceInfo';

type InnerCallback<T, V = void> = (data: T) => V;

interface ChipGroupTheme {
  itemStyle: ChipGroupStyleTheme;
  chipGroupSpace: ChipGroupSpaceOptions;
  chipGroupPadding: ChipGroupPaddingOptions;
  chipBackgroundSystemMaterial: uiMaterial.Material;
  chipSelectedBackgroundSystemMaterial: uiMaterial.Material;
  iconBackgroundSystemMaterial: uiMaterial.Material;
}

const noop = (selectedIndexes: Array<int>) => {
}

const colorStops: Array<[ResourceColor, number]> = [['rgba(0, 0, 0, 1)', 0], ['rgba(0, 0, 0, 0)', 1]]
const defaultTheme: ChipGroupTheme = {
  itemStyle: {
    size: ChipSize.NORMAL,
    backgroundColor: $r('app.string.app_name'),
    fontColor: $r('app.string.app_name'),
    selectedFontColor: $r('app.string.app_name'),
    selectedBackgroundColor: $r('app.string.app_name'),
    fillColor: $r('app.string.app_name'),
    selectedFillColor: $r('app.string.app_name'),
  },
  chipGroupSpace: { itemSpace: 8, startSpace: 16, endSpace: 16 },
  chipGroupPadding: { top: 14, bottom: 14 },
  chipBackgroundSystemMaterial: new uiMaterial.ImmersiveMaterial({
    style: uiMaterial.ImmersiveStyle.ULTRA_THIN
  }),
  chipSelectedBackgroundSystemMaterial: new uiMaterial.ImmersiveMaterial({
    style: uiMaterial.ImmersiveStyle.ULTRA_THIN,
    materialColor: $r('app.string.app_name')
  }),
  iconBackgroundSystemMaterial: new uiMaterial.ImmersiveMaterial({
    style: uiMaterial.ImmersiveStyle.ULTRA_THIN
  })
}

const iconGroupSuffixTheme: IconGroupSuffixTheme = {
  backgroundColor: $r('app.string.app_name'),
  borderRadius: $r('app.string.app_name'),
  smallIconSize: 16,
  normalIconSize: 24,
  smallBackgroundSize: 28,
  normalBackgroundSize: 36,
  marginLeft: 8,
  marginRight: 16,
  fillColor: $r('app.string.app_name'),
  defaultEffect: -1
}

enum ChipGroupHeight {
  NORMAL = 36,
  SMALL = 28,
}

export interface IconOptions {
  src: ResourceStr;
  size?: SizeOptions;
}

export interface ChipGroupPaddingOptions {
  top: Length;
  bottom: Length;
}

interface ChipGroupStyleTheme {
  size: ChipSize | SizeOptions;
  backgroundColor: ResourceColor;
  fontColor: ResourceColor;
  selectedFontColor: ResourceColor;
  selectedBackgroundColor: ResourceColor;
  fillColor: ResourceColor;
  selectedFillColor: ResourceColor;
}

export interface ChipItemLabelOptions {
  text: string;
}

export interface SuffixImageIconOptions extends IconOptions {
  action?: VoidCallback;
  accessibilityText?: ResourceStr;
  accessibilityDescription?: ResourceStr;
  accessibilityLevel?: string;
}

export interface ChipGroupItemOptions {
  prefixIcon?: IconOptions;
  prefixSymbol?: ChipSymbolGlyphOptions;
  label: ChipItemLabelOptions;
  suffixImageIcon?: SuffixImageIconOptions;
  suffixSymbol?: ChipSymbolGlyphOptions;
  suffixSymbolOptions?: ChipSuffixSymbolGlyphOptions;
  allowClose?: boolean;
  closeOptions?: CloseOptions;
  accessibilityDescription?: ResourceStr;
  accessibilityLevel?: string;
}

export interface ChipItemStyle {
  size?: ChipSize | SizeOptions;
  backgroundColor?: ResourceColor;
  fontColor?: ResourceColor;
  selectedFontColor?: ResourceColor;
  selectedBackgroundColor?: ResourceColor;
}

export interface ChipGroupSpaceOptions {
  itemSpace?: number | string;
  startSpace?: Length;
  endSpace?: Length;
}

export interface IconItemOptions {
  icon: IconOptions;
  action: VoidCallback;
  accessibilityText?: ResourceStr;
  accessibilityDescription?: ResourceStr;
  accessibilityLevel?: string;
}

export interface SymbolItemOptions {
  symbol: SymbolGlyphModifier;
  action: VoidCallback;
  accessibilityText?: ResourceStr;
  accessibilityDescription?: ResourceStr;
  accessibilityLevel?: string;
}

interface IconGroupSuffixTheme {
  smallIconSize: number;
  normalIconSize: number;
  backgroundColor: ResourceColor;
  smallBackgroundSize: number;
  normalBackgroundSize: number;
  borderRadius: Dimension;
  marginLeft: number;
  marginRight: number;
  fillColor: ResourceColor;
  defaultEffect: number;
}

function getChipItemStyle(tar: ChipGroupStyleTheme) {
  return {
    size: tar.size,
    backgroundColor: tar.backgroundColor,
    fontColor: tar.fontColor,
    selectedFontColor: tar.selectedFontColor,
    selectedBackgroundColor: tar.selectedBackgroundColor
  } as ChipItemStyle;
}

function parseDimension<T>(
  uiContext: UIContext,
  value: Dimension | Length | undefined,
  isValid: InnerCallback<string, boolean>,
  defaultValue: T
): T {
  if (value === undefined || value === null) {
    return defaultValue;
  }
  const resourceManager = uiContext.getHostContext()?.resourceManager;
  if (!resourceManager) {
    return defaultValue;
  }
  if (typeof value === 'object') {
    let temp: Resource = value as Resource;
    if (temp.type === 10002 || temp.type === 10007) {
      if (resourceManager && resourceManager.getDouble(temp.id) >= 0) {
        return value as T;
      }
    } else if (temp.type === 10003) {
      let stringValue: string = '';
      try {
        stringValue = resourceManager.getStringSync(temp.id);
      } catch (err) {
        stringValue = '';
      }
      if (resourceManager && isValidDimensionString(stringValue)) {
        return value as T;
      }
    }
  } else if (typeof value === 'number') {
    if (value as number >= 0) {
      return value as T;
    }
  } else if (typeof value === 'string') {
    if (isValid(value as string)) {
      return value as T;
    }
  }
  return defaultValue;
}

function isValidString(dimension: string, regex: RegExp): boolean {
  const matches = dimension.match(regex);
  if (!matches || matches.length < 3 || !matches[1]) {
    return false;
  }
  const value = Number.parseFloat(matches[1]!);
  return value >= 0;
}

function isValidDimensionString(dimension: string): boolean {
  return isValidString(dimension, new RegExp('(-?\\d+(?:\\.\\d+)?)_?(fp|vp|px|lpx|%)?$', 'i'));
}

function isValidDimensionNoPercentageString(dimension: string): boolean {
  return isValidString(dimension, new RegExp('(-?\\d+(?:\\.\\d+)?)_?(fp|vp|px|lpx)?$', 'i'));
}

function toStringFormat(resource: ResourceStr | undefined): string {
  try {
    if (typeof resource === 'undefined') {
      return '';
    } else if (typeof resource === 'string') {
      return resource as string;
    } else {
      return resourceManager.getSysResourceManager().getStringSync((resource as Resource).id);
    }
  } catch (error) {
    let code: number | undefined = (error as ClassCastError).code;
    let message: string | undefined = (error as ClassCastError).message;
    hilog.error(0x3900, 'Chip',
      `toStringFormat error, code: ${code}, message: ${message}`);
    return '';
  }
}

@Component
export struct IconGroupSuffix {
  @Consume chipSize: ChipSize | SizeOptions;
  @State refreshCnt: int = 0;
  @Watch('onItems')
  @PropRef items: (IconItemOptions | SymbolGlyphModifier | SymbolItemOptions)[] =
    new Array<IconItemOptions | SymbolGlyphModifier | SymbolItemOptions>();
  @PropRef iconBackgroundSystemMaterial?: uiMaterial.Material = undefined;
  symbolEffect: SymbolEffect = new SymbolEffect();

  private onItems(_: string): void {
    this.refreshCnt++;
  }

  private getBackgroundSize(): number {
    if (this.chipSize === ChipSize.SMALL) {
      return iconGroupSuffixTheme.smallBackgroundSize;
    } else {
      return iconGroupSuffixTheme.normalBackgroundSize;
    }
  }

  private getIconSize(val?: Length): Length {
    if (val === undefined) {
      return this.chipSize === ChipSize.SMALL ?
        iconGroupSuffixTheme.smallIconSize :
        iconGroupSuffixTheme.normalIconSize;
    }
    let value: Length;
    if (this.chipSize === ChipSize.SMALL) {
      value = parseDimension(this.getUIContext(), val, isValidDimensionString, iconGroupSuffixTheme.smallIconSize);
    } else {
      value = parseDimension(this.getUIContext(), val, isValidDimensionString, iconGroupSuffixTheme.normalIconSize);
    }
    return value;
  }

  @Builder
  SymbolItemBuilder(item: SymbolItemOptions): void {
    SymbolGlyph()
      .fontColor([iconGroupSuffixTheme.fillColor])
      .fontSize(this.getIconSize())
      .attributeModifier(item.symbol)
      .focusable(true)
      .effectStrategy(SymbolEffectStrategy.NONE)
      .symbolEffect(this.symbolEffect, false)
      .symbolEffect(this.symbolEffect, Double.toInt(iconGroupSuffixTheme.defaultEffect))
  }

  @Builder
  IconItemBuilder(item: IconItemOptions): void {
    Image(item.icon.src)
      .fillColor(iconGroupSuffixTheme.fillColor)
      .size({
        width: this.getIconSize(item.icon.size?.width),
        height: this.getIconSize(item.icon.size?.height)
      })
      .focusable(true)
  }

  @Builder
  IconButtonsBuilder(material: uiMaterial.Material | undefined): void {
    Row({ space: 8 } as RowOptions) {
      ForEach(this.items, (suffixItem: IconItemOptions | SymbolGlyphModifier | SymbolItemOptions) => {
        Button({ type: ButtonType.Normal } as ButtonOptions) {
          if (suffixItem instanceof SymbolGlyphModifier) {
            SymbolGlyph()
              .fontColor([iconGroupSuffixTheme.fillColor])
              .fontSize(this.getIconSize())
              .attributeModifier(suffixItem as SymbolGlyphModifier)
              .focusable(true)
              .effectStrategy(SymbolEffectStrategy.NONE)
              .symbolEffect(this.symbolEffect, false)
              .symbolEffect(this.symbolEffect, Double.toInt(iconGroupSuffixTheme.defaultEffect))
          } else if (suffixItem instanceof SymbolItemOptions) {
            this.SymbolItemBuilder(suffixItem as SymbolItemOptions)
          } else if (suffixItem instanceof IconItemOptions) {
            this.IconItemBuilder(suffixItem as IconItemOptions)
          }
        }
        .size({
          width: this.getBackgroundSize(),
          height: this.getBackgroundSize()
        })
        .systemMaterial(material)
        .backgroundColor(iconGroupSuffixTheme.backgroundColor)
        .borderRadius(iconGroupSuffixTheme.borderRadius)
        .accessibilityText(this.getAccessibilityText(suffixItem))
        .accessibilityDescription(this.getAccessibilityDescription(suffixItem))
        .accessibilityLevel(this.getAccessibilityLevel(suffixItem))
        .onClick(() => {
          if (suffixItem instanceof IconItemOptions) {
            (suffixItem as IconItemOptions).action();
          }
          if (suffixItem instanceof SymbolItemOptions) {
            (suffixItem as SymbolItemOptions).action();
          }
        })
      }, (suffixItem: IconItemOptions | SymbolGlyphModifier | SymbolItemOptions, index: int) => {
        return `${this.refreshCnt}_${index}`;
      })
    }
  }

  build(): void {
    if (deviceInfo.sdkApiVersion >= 26) {
      if (enableEffectComponent(this.iconBackgroundSystemMaterial)) {
        EffectComponent() {
          this.IconButtonsBuilder(
            createSubECMaterial(
              withDefaultMaterial(this.iconBackgroundSystemMaterial, defaultTheme.iconBackgroundSystemMaterial)
            )
          )
        }
        .systemMaterial(
          createECMaterial(
            withDefaultMaterial(this.iconBackgroundSystemMaterial, defaultTheme.iconBackgroundSystemMaterial)
          )
        )
      } else {
        this.IconButtonsBuilder(
          withDefaultMaterial(this.iconBackgroundSystemMaterial, defaultTheme.iconBackgroundSystemMaterial)
        )
      }
    } else {
      this.IconButtonsBuilder(undefined)
    }
  }

  private isSymbolItem(item: IconItemOptions | SymbolItemOptions): boolean {
    return item instanceof SymbolItemOptions;
  }

  private getAccessibilityLevel(item: IconItemOptions | SymbolGlyphModifier | SymbolItemOptions): string {
    if (item instanceof SymbolGlyphModifier) {
      return 'auto';
    }
    return item.accessibilityLevel ?? 'auto';
  }

  private getAccessibilityDescription(
    item: IconItemOptions | SymbolGlyphModifier | SymbolItemOptions
  ): string {
    if (item instanceof SymbolGlyphModifier || typeof item.accessibilityDescription === 'undefined') {
      return '';
    }
    return toStringFormat(item.accessibilityDescription);
  }

  private getAccessibilityText(item: IconItemOptions | SymbolGlyphModifier | SymbolItemOptions): string {
    if (item instanceof SymbolGlyphModifier || typeof item.accessibilityText === 'undefined') {
      return '';
    }
    return toStringFormat(item.accessibilityText);
  }
}

@Builder
export type ChipGroupSuffixBuilder = () => void;

export interface ChipItemsBuilderOptions {
  backgroundSystemMaterial?: uiMaterial.Material;
  activatedBackgroundSystemMaterial?: uiMaterial.Material;
}

@Component
export struct ChipGroup {
  @PropRef @Watch('onItemsChange') items: ChipGroupItemOptions[] = new Array<ChipGroupItemOptions>();
  @PropRef @Watch('itemStyleOnChange') itemStyle?: ChipItemStyle = getChipItemStyle(defaultTheme.itemStyle);
  @Provide chipSize: ChipSize | SizeOptions = defaultTheme.itemStyle.size;
  @PropRef selectedIndexes?: Array<int> = [0];
  @PropRef @Watch('onMultipleChange') multiple?: boolean = false;
  @PropRef chipGroupSpace?: ChipGroupSpaceOptions = defaultTheme.chipGroupSpace;
  @PropRef backgroundSystemMaterial?: uiMaterial.Material = undefined;
  @PropRef selectedBackgroundSystemMaterial?: uiMaterial.Material = undefined;
  @BuilderParam suffix?: ChipGroupSuffixBuilder;
  public onChange: InnerCallback<Array<int>> = noop;
  private scroller: Scroller = new Scroller();
  @State isReachEnd: boolean = false;
  @PropRef chipGroupPadding?: ChipGroupPaddingOptions = defaultTheme.chipGroupPadding;
  @State refreshCnt: int = 0;

  onItemsChange(value: string): void {
    this.refreshCnt++;
  }

  onMultipleChange(value: string): void {
    this.selectedIndexes = this.getSelectedIndexes();
  }

  itemStyleOnChange(value?: string): void {
    this.chipSize = this.getChipSize();
  }

  aboutToAppear(): void {
    this.itemStyleOnChange();
    if (this.getSelectedIndexes().length === 0) {
      this.selectedIndexes = [0];
    }
  }

  private getChipSize(): ChipSize | SizeOptions {
    if (this.itemStyle && this.itemStyle!.size) {
      if (this.itemStyle!.size instanceof SizeOptions) {
        const sizeOptions = this.itemStyle!.size as SizeOptions;
        if (!sizeOptions.width || !sizeOptions.height) {
          return defaultTheme.itemStyle.size!;
        }
      }
      return this.itemStyle!.size!;
    }
    return defaultTheme.itemStyle.size;
  }

  private getFontColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.fontColor) {
      if (typeof this.itemStyle!.fontColor === 'object') {
        let temp: Resource = this.itemStyle!.fontColor! as Resource;
        if (temp == undefined || temp == null) {
          return defaultTheme.itemStyle.fontColor;
        }
        if (temp.type === 10001) {
          return this.itemStyle!.fontColor!;
        }
        return defaultTheme.itemStyle.fontColor;
      }
      return this.itemStyle!.fontColor!;
    }
    return defaultTheme.itemStyle.fontColor;
  }

  private getSelectedFontColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.selectedFontColor) {
      if (typeof this.itemStyle!.selectedFontColor === 'object') {
        let temp: Resource = this.itemStyle!.selectedFontColor as Resource;
        if (temp == undefined || temp == null) {
          return defaultTheme.itemStyle.selectedFontColor;
        }
        if (temp.type === 10001) {
          return this.itemStyle!.selectedFontColor!;
        }
        return defaultTheme.itemStyle.selectedFontColor;
      }
      return this.itemStyle!.selectedFontColor!;
    }
    return defaultTheme.itemStyle.selectedFontColor;
  }

  private getFillColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.fontColor) {
      return this.itemStyle!.fontColor!;
    }
    return defaultTheme.itemStyle.fillColor;
  }

  private getSelectedFillColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.selectedFontColor) {
      return this.itemStyle!.selectedFontColor!;
    }
    return defaultTheme.itemStyle.selectedFillColor;
  }

  private getBackgroundColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.backgroundColor) {
      if (typeof this.itemStyle!.backgroundColor === 'object') {
        let temp: Resource = this.itemStyle!.backgroundColor! as Resource;
        if (temp == undefined || temp == null) {
          return defaultTheme.itemStyle.backgroundColor;
        }
        if (temp.type === 10001) {
          return this.itemStyle!.backgroundColor!;
        }
        return defaultTheme.itemStyle.backgroundColor;
      }
      return this.itemStyle!.backgroundColor!;
    }
    return defaultTheme.itemStyle.backgroundColor;
  }

  private getSelectedBackgroundColor(): ResourceColor {
    if (this.itemStyle && this.itemStyle!.selectedBackgroundColor) {
      if (typeof this.itemStyle!.selectedBackgroundColor === 'object') {
        let temp: Resource = this.itemStyle!.selectedBackgroundColor as Resource;
        if (temp == undefined || temp == null) {
          return defaultTheme.itemStyle.selectedBackgroundColor;
        }
        if (temp.type === 10001) {
          return this.itemStyle!.selectedBackgroundColor!;
        }
        return defaultTheme.itemStyle.selectedBackgroundColor;
      }
      return this.itemStyle!.selectedBackgroundColor!;
    }
    return defaultTheme.itemStyle.selectedBackgroundColor;
  }

  private getSelectedIndexes(): Array<int> {
    let temp: int[] = [];
    temp = (this.selectedIndexes ?? [0]).filter(
      (element, index, array) => {
        return (
          element >= 0 &&
            element != null &&
            element != undefined &&
            array.indexOf(element) === index &&
            element < (this.items || [] as Array<int>).length);
      });
    return temp;
  }

  private isMultiple(): boolean {
    return this.multiple ?? false;
  }

  private getChipGroupItemSpace() {
    if (this.chipGroupSpace == undefined) {
      return defaultTheme.chipGroupSpace.itemSpace
    }
    return parseDimension(
      this.getUIContext(),
      this.chipGroupSpace!.itemSpace,
      isValidDimensionNoPercentageString,
      defaultTheme.chipGroupSpace.itemSpace
    );
  }

  private getChipGroupStartSpace() {
    if (this.chipGroupSpace == undefined) {
      return defaultTheme.chipGroupSpace.startSpace
    }
    return parseDimension(
      this.getUIContext(),
      this.chipGroupSpace!.startSpace,
      isValidDimensionNoPercentageString,
      defaultTheme.chipGroupSpace.startSpace
    );
  }

  private getChipGroupEndSpace() {
    if (this.chipGroupSpace == undefined) {
      return defaultTheme.chipGroupSpace.endSpace
    }
    return parseDimension(
      this.getUIContext(),
      this.chipGroupSpace!.endSpace,
      isValidDimensionNoPercentageString,
      defaultTheme.chipGroupSpace.endSpace
    );
  }

  private getOnChange(): (selectedIndexes: Array<int>) => void {
    return this.onChange ?? noop;
  }

  private isSelected(itemIndex: int): boolean {
    if (!this.isMultiple() && this.getSelectedIndexes().length > 0) {
      return itemIndex == this.getSelectedIndexes()[0];
    } else {
      return this.getSelectedIndexes().some((element, index, array) => {
        return (element == itemIndex);
      })
    }
  }

  private getPaddingTop() {
    if (!this.chipGroupPadding || !this.chipGroupPadding!.top) {
      return defaultTheme.chipGroupPadding.top;
    }
    return parseDimension(
      this.getUIContext(),
      this.chipGroupPadding!.top,
      isValidDimensionNoPercentageString,
      defaultTheme.chipGroupPadding.top
    );
  }

  private getPaddingBottom() {
    if (!this.chipGroupPadding || !this.chipGroupPadding!.bottom) {
      return defaultTheme.chipGroupPadding.bottom;
    }
    return parseDimension(
      this.getUIContext(),
      this.chipGroupPadding!.bottom,
      isValidDimensionNoPercentageString,
      defaultTheme.chipGroupPadding.bottom
    );
  }

  private getChipGroupHeight(): double {
    if (typeof this.chipSize === 'string') {
      if (this.chipSize === ChipSize.NORMAL) {
        return ChipGroupHeight.NORMAL;
      } else {
        return ChipGroupHeight.SMALL;
      }
    } else if (this.chipSize instanceof SizeOptions) {
      return (this.chipSize as SizeOptions).height as double;
    } else {
      return ChipGroupHeight.NORMAL
    }
  }

  private getBackgroundSystemMaterial(): uiMaterial.Material | undefined {
    return withDefaultMaterial(this.backgroundSystemMaterial, defaultTheme.chipBackgroundSystemMaterial);
  }

  private getSelectedBackgroundSystemMaterial(): uiMaterial.Material | undefined {
    return withDefaultMaterial(
      this.selectedBackgroundSystemMaterial,
      defaultTheme.chipSelectedBackgroundSystemMaterial
    );
  }

  private getOutsideBlendType(): BlendApplyType | undefined {
    if (!this.suffix && (!!this.getBackgroundSystemMaterial() || !!this.getSelectedBackgroundSystemMaterial())) {
      return undefined;
    }
    return BlendApplyType.OFFSCREEN;
  }

  private getOutsideBlendMode(): BlendMode | undefined {
    if (!this.suffix && (!!this.getBackgroundSystemMaterial() || !!this.getSelectedBackgroundSystemMaterial())) {
      return undefined;
    }
    return BlendMode.SRC_OVER;
  }

  @Builder
  ChipItemsBuilder(options: ChipItemsBuilderOptions): void {
    Row({ space: this.getChipGroupItemSpace() } as RowOptions) {
      ForEach(this.items, (chipItem: ChipGroupItemOptions, index: int) => {
        if (chipItem) {
          Chip({
            prefixIcon: this.getPrefixIcon(chipItem),
            prefixSymbol: chipItem?.prefixSymbol,
            label: {
              text: chipItem?.label?.text ?? ' ',
              fontColor: this.getFontColor(),
              activatedFontColor: this.getSelectedFontColor(),
            } as LabelOptions,
            suffixIcon: this.getSuffixIcon(chipItem),
            suffixSymbol: chipItem?.suffixSymbol,
            suffixSymbolOptions: chipItem.suffixSymbolOptions,
            allowClose: chipItem.allowClose ?? false,
            closeOptions: chipItem.closeOptions,
            enabled: true,
            activated: this.isSelected(index),
            backgroundColor: this.getBackgroundColor(),
            backgroundSystemMaterial: options.backgroundSystemMaterial,
            activatedBackgroundSystemMaterial: options.activatedBackgroundSystemMaterial,
            size: this.getChipSize(),
            activatedBackgroundColor: this.getSelectedBackgroundColor(),
            accessibilitySelectedType:
            this.multiple ? AccessibilitySelectedType.CHECKED : AccessibilitySelectedType.SELECTED,
            accessibilityDescription: chipItem.accessibilityDescription,
            accessibilityLevel: chipItem.accessibilityLevel,
            onClicked: () => {
              if (this.isSelected(index)) {
                if (!(!this.isMultiple())) {
                  if (this.getSelectedIndexes().length > 1) {
                    this.selectedIndexes = this.selectedIndexes!.filter((v, _) => {
                      return v !== index
                    })
                  }
                }
              } else {
                if (!this.selectedIndexes || this.selectedIndexes!.length === 0) {
                  this.selectedIndexes = this.getSelectedIndexes();
                }
                if (!this.isMultiple()) {
                  this.selectedIndexes = [];
                }
                this.selectedIndexes!.push(index);
              }
              this.getOnChange()(this.getSelectedIndexes());
            }
          } as ChipOptions)
        }
      }, (chipItem: ChipGroupItemOptions, index: int) => {
        return `${this.refreshCnt}_${index}`;
      });
    }
    .padding({
      left: this.getChipGroupStartSpace(),
      right: this.getChipGroupEndSpace()
    } as Padding)
    .constraintSize({ minWidth: '100%' })
  }

  build(): void {
    Row() {
      Stack() {
        Scroll(this.scroller) {
          if (deviceInfo.sdkApiVersion >= 26) {
            if (enableEffectComponent(this.backgroundSystemMaterial)) {
              EffectComponent() {
                this.ChipItemsBuilder({
                  backgroundSystemMaterial: createSubECMaterial(this.getBackgroundSystemMaterial()),
                  activatedBackgroundSystemMaterial: this.getSelectedBackgroundSystemMaterial()
                })
              }
              .systemMaterial(createECMaterial(this.getBackgroundSystemMaterial()))
            } else {
              this.ChipItemsBuilder({
                backgroundSystemMaterial: this.getBackgroundSystemMaterial(),
                activatedBackgroundSystemMaterial: this.getSelectedBackgroundSystemMaterial()
              })
            }
          } else {
            this.ChipItemsBuilder({})
          }
        }
        .scrollable(ScrollDirection.Horizontal)
        .scrollBar(BarState.Off)
        .align(Alignment.Start)
        .width('100%')
        .clip(false)
        .onDidScroll(() => {
          this.isReachEnd = this.scroller.isAtEnd();
        })

        if (this.suffix && !this.isReachEnd) {
          Stack()
            .width(iconGroupSuffixTheme.normalBackgroundSize)
            .height(this.getChipGroupHeight())
            .linearGradient({ angle: 90, colors: colorStops })
            .blendMode(BlendMode.DST_IN, BlendApplyType.OFFSCREEN)
            .hitTestBehavior(HitTestMode.None)
        }
      }
      .padding({ top: this.getPaddingTop(), bottom: this.getPaddingBottom() } as Padding)
      .layoutWeight(1)
      .blendMode(this.getOutsideBlendMode(), this.getOutsideBlendType())
      .alignContent(Alignment.End)

      if (this.suffix) {
        Row() {
          this.suffix!();
        }.padding({
          left: iconGroupSuffixTheme.marginLeft,
          right: iconGroupSuffixTheme.marginRight
        } as Padding)
      }
    }

    .align(Alignment.End)
    .width('100%')
  }

  getPrefixIcon(chipItem: ChipGroupItemOptions): PrefixIconOptions {
    return {
      src: chipItem.prefixIcon?.src ?? '',
      size: chipItem.prefixIcon?.size ?? undefined,
      fillColor: this.getFillColor(),
      activatedFillColor: this.getSelectedFillColor()
    };
  }

  private getSuffixIcon(chipItem: ChipGroupItemOptions): SuffixIconOptions | undefined {
    if (!!chipItem.suffixImageIcon) {
      return {
        src: chipItem.suffixImageIcon!.src,
        size: chipItem.suffixImageIcon!.size,
        fillColor: this.getFillColor(),
        activatedFillColor: this.getSelectedFillColor(),
        action: chipItem.suffixImageIcon!.action,
        accessibilityText: chipItem.suffixImageIcon!.accessibilityText,
        accessibilityDescription: chipItem.suffixImageIcon!.accessibilityDescription,
        accessibilityLevel: chipItem.suffixImageIcon!.accessibilityLevel,
      } as SuffixIconOptions;
    }
    return undefined;
  }
}

function withDefaultMaterial(
  material: uiMaterial.Material | undefined, defaultMaterial: uiMaterial.Material
): uiMaterial.Material | undefined {
  return material;
}

function enableEffectComponent(
  material: uiMaterial.Material | undefined
): boolean {
  return false;
}

function createECMaterial(material: uiMaterial.Material | undefined): uiMaterial.Material | undefined {
  return material;
}

function createSubECMaterial(material: uiMaterial.Material | undefined): uiMaterial.Material | undefined {
  return material;
}
