/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const whiteList = new Set([
  'ASTCResource', 'AbstractProperty', 'AccelerationOptions', 'AccessibilityAction',
  'AccessibilityActionInterceptResult', 'AccessibilityCallback', 'AccessibilityHoverEvent',
  'AccessibilityHoverType', 'AccessibilityOptions', 'AccessibilityRoleType',
  'AccessibilitySamePageMode', 'ActionSheet', 'ActionSheetButtonOptions', 'ActionSheetOffset',
  'ActionSheetOptions', 'AdaptiveColor', 'AdsBlockedDetails', 'Affinity', 'AlertDialog',
  'AlertDialogButtonBaseOptions', 'AlertDialogButtonOptions', 'AlertDialogParam',
  'AlertDialogParamWithButtons', 'AlertDialogParamWithConfirm', 'AlertDialogParamWithOptions',
  'AlignRuleOption', 'Alignment', 'AlphabetIndexerOptions', 'AnchoredColorMode',
  'AnimatableArithmetic', 'AnimatableExtend', 'AnimateParam', 'AnimationExtender',
  'AnimationMode', 'AnimationPropertyType', 'AnimationRange', 'AnimationStatus',
  'AnimatorInterface', 'AppRotation', 'AppStorage', 'AppearSymbolEffect', 'Area',
  'ArrowPointPosition', 'ArrowPosition', 'ArrowStyle', 'AutoCapitalizationMode',
  'AutoPlayOptions', 'AvailableLayoutArea', 'AvoidanceMode', 'Axis', 'AxisAction',
  'AxisEvent', 'AxisModel', 'BackgroundBlurStyleOptions', 'BackgroundBrightnessOptions',
  'BackgroundColorStyle', 'BackgroundEffectOptions', 'BackgroundImageOptions', 'BadgeParam',
  'BadgeParamWithNumber', 'BadgeParamWithString', 'BadgePosition', 'BadgeStyle',
  'BarGridColumnOptions', 'BarMode', 'BarPosition', 'BarState', 'BarStyle',
  'BarrierDirection', 'BarrierStyle', 'BaseCustomComponent', 'BaseEvent', 'BaseGestureEvent',
  'BaseHandlerOptions', 'BaseShape', 'BaseSpan', 'BaselineOffsetStyle', 'Bias', 'BindOptions',
  'BlendApplyType', 'BlendMode', 'Blender', 'BlurOptions', 'BlurStyle',
  'BlurStyleActivePolicy', 'BlurStyleOptions', 'BoardStyle', 'BorderImageOption',
  'BorderOptions', 'BorderRadiuses', 'BorderStyle', 'BottomTabBarStyle', 'BounceSymbolEffect',
  'BreakPoints', 'BreakpointsReference', 'Builder', 'BuilderAttachment',
  'BuilderAttachmentInterface', 'BuilderParam', 'BusinessError', 'ButtonConfiguration',
  'ButtonIconOptions', 'ButtonOptions', 'ButtonRole', 'ButtonStyle', 'ButtonStyleMode',
  'ButtonTriggerClickCallback', 'ButtonType', 'CacheMode', 'CalendarAlign',
  'CalendarController', 'CalendarDay', 'CalendarDialogOptions', 'CalendarOptions',
  'CalendarPickerDialog', 'CalendarRequestedData', 'CalendarSelectedDate', 'Callback',
  'CallbackBuffer', 'CallbackKind', 'CallbackResource', 'CallbackResourceHolder',
  'CancelButtonOptions', 'CancelButtonStyle', 'CancelButtonSymbolOptions', 'CanvasDirection',
  'CanvasFillRule', 'CanvasGradient', 'CanvasLineCap', 'CanvasLineJoin', 'CanvasOptions',
  'CanvasPath', 'CanvasPattern', 'CanvasRenderer', 'CanvasRenderingContext2D',
  'CanvasTextAlign', 'CanvasTextBaseline', 'CapsuleStyleOptions', 'CaretOffset', 'CaretStyle',
  'ChainAnimationOptions', 'ChainEdgeEffect', 'ChainStyle', 'ChainWeightOptions',
  'CheckBoxConfiguration', 'CheckBoxShape', 'CheckboxGroupOptions', 'CheckboxGroupResult',
  'CheckboxOptions', 'ChildHitFilterOption', 'ChildrenMainSize', 'CircleOptions',
  'CircleShape', 'CircleStyleOptions', 'ClickEffect', 'ClickEffectLevel', 'ClickEvent',
  'ClientAuthenticationHandler', 'CloseSwipeActionOptions', 'Color', 'ColorContent',
  'ColorFilter', 'ColorMetrics', 'ColorMode', 'ColorSpace', 'ColorStop', 'ColoringStrategy',
  'ColumnOptions', 'ColumnOptionsV2', 'ColumnSplitDividerStyle', 'CommonConfiguration',
  'CommonProgressStyleOptions', 'CommonShape', 'CommonShapeMethod', 'CommonTransition',
  'ComponentContent', 'ComponentOptions', 'ComponentRoot', 'Configuration',
  'ConsoleMessage', 'ConstraintSizeOptions', 'Content', 'ContentClipMode', 'ContentCoverOptions',
  'ContentDidScrollCallback', 'ContentType', 'Context', 'ContextMenu',
  'ContextMenuAnimationOptions', 'ContextMenuEditStateFlags', 'ContextMenuInputFieldType',
  'ContextMenuMediaType', 'ContextMenuOptions', 'ContextMenuSourceType', 'ControlSize',
  'ControllerHandler', 'CopyEvent', 'CopyOptions', 'CrownAction', 'CrownEvent',
  'CrownSensitivity', 'CurrentDayStyle', 'Curve', 'CustomBuilder', 'CustomComponent',
  'CustomComponentV2', 'CustomDialogController', 'CustomDialogControllerOptions',
  'CustomNodeBuilder', 'CustomPopupOptions', 'CustomSpan', 'CustomSpanDrawInfo',
  'CustomSpanMeasureInfo', 'CustomSpanMetrics', 'CustomTheme', 'CutEvent',
  'DataAddOperation', 'DataChangeListener', 'DataChangeOperation', 'DataDeleteOperation',
  'DataExchangeOperation', 'DataMoveOperation', 'DataOperation', 'DataOperationType',
  'DataPanelConfiguration', 'DataPanelOptions', 'DataPanelShadowOptions', 'DataPanelType',
  'DataReloadOperation', 'DataResubmissionHandler', 'DatePickerDialog',
  'DatePickerDialogOptions', 'DatePickerMode', 'DatePickerOptions', 'DatePickerResult',
  'DateRange', 'DateTimeOptions', 'DecorationStyle', 'DecorationStyleInterface',
  'DecorationStyleResult', 'Degree', 'DeleteValue', 'Deserializer', 'DialogAlignment',
  'DialogButtonDirection', 'DialogButtonStyle', 'DialogDisplayMode', 'DigitIndicator',
  'Dimension', 'Direction', 'DirectionalEdgesT', 'DisableSymbolEffect', 'DisappearSymbolEffect',
  'DismissContentCoverAction', 'DismissContinueReason', 'DismissDialogAction',
  'DismissFollowUpAction', 'DismissMenuAction', 'DismissPopupAction', 'DismissReason',
  'DismissSheetAction', 'DistributionType', 'DisturbanceFieldOptions', 'DisturbanceFieldShape',
  'DividerMode', 'DividerOptions', 'DividerStyle', 'DividerStyleOptions', 'DotIndicator',
  'DoubleAnimationParam', 'DpiFollowStrategy', 'DragBehavior', 'DragEvent',
  'DragInteractionOptions', 'DragItemInfo', 'DragPointCoordinate', 'DragPreviewLiftingScale',
  'DragPreviewMode', 'DragPreviewOptions', 'DragResult', 'DraggingSizeChangeEffect',
  'DrawContext', 'DrawModifier', 'DrawableDescriptor', 'DrawingCanvas', 'DrawingColorFilter',
  'DrawingLattice', 'DrawingRenderingContext', 'DropOptions', 'DynamicNode',
  'DynamicRangeMode', 'EclipseStyleOptions', 'Edge', 'EdgeColors', 'EdgeEffect',
  'EdgeEffectOptions', 'EdgeOutlineStyles', 'EdgeOutlineWidths', 'EdgeStyles', 'EdgeWidth',
  'EdgeWidths', 'Edges', 'EditMenuOptions', 'EditMode', 'EditableTextChangeValue',
  'EditableTextOnChangeCallback', 'EffectDirection', 'EffectEdge', 'EffectFillStyle',
  'EffectScope', 'EffectType', 'EllipseOptions', 'EllipseShape', 'EllipsisMode',
  'EmbeddedDpiFollowStrategy', 'EmbeddedOptions', 'EmbeddedType',
  'EmbeddedWindowModeFollowStrategy', 'EmitterOptions', 'EmitterParticleOptions',
  'EmitterProperty', 'EnterKeyType', 'Entry', 'EntryOptions', 'EnvPropsOptions',
  'Environment', 'ErrorCallback', 'Event', 'EventEmulator', 'EventLocationInfo',
  'EventQueryType', 'EventResult', 'EventTarget', 'EventTargetInfo', 'ExchangeIndex',
  'ExchangeKey', 'ExpandedMenuItemOptions', 'ExpectedFrameRateRange', 'Extend', 'FP',
  'FadingEdgeOptions', 'FileSelectorMode', 'FileSelectorParam', 'FileSelectorResult',
  'FillMode', 'Filter', 'FingerInfo', 'FinishCallbackType', 'FirstMeaningfulPaint',
  'FlexAlign', 'FlexDirection', 'FlexOptions', 'FlexSpaceOptions', 'FlexWrap',
  'FocusAxisEvent', 'FocusBoxStyle', 'FocusController', 'FocusDrawLevel', 'FocusMovement',
  'FocusPriority', 'FocusWrapMode', 'FoldStatus', 'FolderStackOptions', 'Font',
  'FontInfo', 'FontOptions', 'FontSettingOptions', 'FontStyle', 'FontWeight',
  'ForegroundBlurStyleOptions', 'ForegroundEffectOptions', 'FormCallbackInfo',
  'FormDimension', 'FormInfo', 'FormLinkOptions', 'FormRenderingMode', 'FormShape',
  'FractionStop', 'FrameNode', 'FrictionMotion', 'FullScreenEnterEvent',
  'FullScreenExitHandler', 'FullscreenInfo', 'FunctionKey', 'GaugeConfiguration',
  'GaugeIndicatorOptions', 'GaugeOptions', 'GaugeShadowOptions', 'GeometryInfo',
  'GeometryTransitionOptions', 'Gesture', 'GestureControl', 'GestureEvent', 'GestureGroup',
  'GestureGroupGestureHandlerOptions', 'GestureGroupHandler', 'GestureHandler',
  'GestureInfo', 'GestureJudgeResult', 'GestureMask', 'GestureMode', 'GestureModifier',
  'GesturePriority', 'GestureRecognizer', 'GestureRecognizerJudgeBeginCallback',
  'GestureRecognizerState', 'GestureStyle', 'GestureType', 'GetItemMainSizeByIndex',
  'GradientDirection', 'GridColColumnOption', 'GridColOptions', 'GridContainerOptions',
  'GridDirection', 'GridItemAlignment', 'GridItemOptions', 'GridItemStyle',
  'GridLayoutOptions', 'GridRowColumnOption', 'GridRowDirection', 'GridRowOptions',
  'GridRowSizeOption', 'GuideLinePosition', 'GuideLineStyle', 'GutterOption',
  'HapticFeedbackMode', 'Header', 'HeightBreakpoint', 'HierarchicalSymbolEffect',
  'HistoricalPoint', 'HitTestMode', 'HitTestType', 'HorizontalAlign', 'HoverCallback',
  'HoverEffect', 'HoverEvent', 'HoverEventParam', 'HoverModeAreaType', 'HttpAuthHandler',
  'ICurve', 'IDataSource', 'IMonitor', 'IMonitorValue', 'IPropertySubscriber',
  'ISinglePropertyChangeSubscriber', 'IconOptions', 'IlluminatedType', 'ImageAIOptions',
  'ImageAnalyzerConfig', 'ImageAnalyzerController', 'ImageAnalyzerType', 'ImageAttachment',
  'ImageAttachmentInterface', 'ImageAttachmentLayoutStyle', 'ImageBitmap',
  'ImageCompleteCallback', 'ImageContent', 'ImageData', 'ImageError', 'ImageErrorCallback',
  'ImageFit', 'ImageFrameInfo', 'ImageInterpolation', 'ImageLoadResult', 'ImageModifier',
  'ImageParticleParameters', 'ImageRenderMode', 'ImageRepeat', 'ImageRotateOrientation',
  'ImageSize', 'ImageSmoothingQuality', 'ImageSourceSize', 'ImageSpanAlignment',
  'IndexerAlign', 'Indicator', 'IndicatorComponentController', 'IndicatorStyle',
  'InputCounterOptions', 'InputType', 'InsertValue', 'IntelligentTrackingPreventionDetails',
  'IntentionCode', 'InteractionHand', 'InterceptionModeCallback', 'InterceptionShowCallback',
  'Interop', 'InvertOptions', 'IsolatedOptions', 'ItemAlign', 'ItemDragEventHandler',
  'ItemDragInfo', 'ItemState', 'JavaScriptProxy', 'JsGeolocation', 'JsResult', 'KVMContext',
  'KeyEvent', 'KeyProcessingMode', 'KeySource', 'KeyType', 'KeyboardAppearance',
  'KeyboardAvoidMode', 'KeyboardOptions', 'KeyframeAnimateParam', 'KeyframeState', 'LPX',
  'LabelStyle', 'LargestContentfulPaint', 'LaunchMode', 'LayoutBorderInfo', 'LayoutChild',
  'LayoutDirection', 'LayoutInfo', 'LayoutManager', 'LayoutMode', 'LayoutPolicy',
  'LayoutSafeAreaEdge', 'LayoutSafeAreaType', 'LayoutStyle', 'Layoutable', 'LazyForEachOps',
  'LeadingMarginPlaceholder', 'Length', 'LengthConstrain', 'LengthMetrics',
  'LengthMetricsUnit', 'LengthUnit', 'LetterSpacingStyle', 'LightSource',
  'LineBreakStrategy', 'LineCapStyle', 'LineHeightStyle', 'LineJoinStyle', 'LineMetrics',
  'LineOptions', 'LineSpacingOptions', 'LinearGradient', 'LinearGradientBlurOptions',
  'LinearGradientOptions', 'LinearIndicatorController', 'LinearIndicatorStartOptions',
  'LinearIndicatorStyle', 'LinearStyleOptions', 'ListDividerOptions', 'ListItemAlign',
  'ListItemGroupArea', 'ListItemGroupOptions', 'ListItemGroupStyle', 'ListItemOptions',
  'ListItemStyle', 'ListOptions', 'ListScroller', 'LoadCommittedDetails', 'Loader',
  'LoadingProgressConfiguration', 'LoadingProgressStyle', 'LocalBuilder', 'LocalStorage',
  'LocalizedAlignRuleOptions', 'LocalizedAlignment', 'LocalizedBarrierDirection',
  'LocalizedBarrierStyle', 'LocalizedBorderRadiuses', 'LocalizedDragPointCoordinate',
  'LocalizedEdgeColors', 'LocalizedEdgeWidths', 'LocalizedEdges',
  'LocalizedHorizontalAlignParam', 'LocalizedMargin', 'LocalizedPadding',
  'LocalizedPosition', 'LocalizedVerticalAlignParam', 'LocationDescription',
  'LocationIconStyle', 'LongPressGesture', 'LongPressGestureEvent', 'LongPressGestureHandler',
  'LongPressGestureHandlerOptions', 'LongPressGestureParams', 'LongPressRecognizer',
  'LunarSwitchStyle', 'Margin', 'MarkStyle', 'MarqueeOptions', 'MarqueeStartPolicy',
  'MarqueeState', 'MarqueeUpdateStrategy', 'Materialized', 'Matrix2D', 'MaxLinesMode',
  'MaxLinesOptions', 'Measurable', 'MeasureOptions', 'MeasureResult', 'MenuAlignType',
  'MenuElement', 'MenuItemConfiguration', 'MenuItemGroupOptions', 'MenuItemOptions',
  'MenuItemOptionsV2', 'MenuMaskType', 'MenuOnAppearCallback', 'MenuOptions',
  'MenuOutlineOptions', 'MenuPolicy', 'MenuPreviewMode', 'MenuType', 'MessageLevel',
  'MixedMode', 'ModalMode', 'ModalTransition', 'ModelType', 'ModifierKey', 'Monitor',
  'MonthData', 'MoreButtonOptions', 'MotionBlurAnchor', 'MotionBlurOptions',
  'MotionPathOptions', 'MouseAction', 'MouseButton', 'MouseEvent', 'MoveIndex',
  'MultiShadowOptions', 'MutableStyledString', 'NativeEmbedDataInfo', 'NativeEmbedInfo',
  'NativeEmbedStatus', 'NativeEmbedTouchInfo', 'NativeEmbedVisibilityInfo',
  'NativeMediaPlayerConfig', 'NativeXComponentParameters', 'NavBar', 'NavBarPosition',
  'NavContentInfo', 'NavDestinationActiveReason', 'NavDestinationCommonTitle',
  'NavDestinationContext', 'NavDestinationCustomTitle', 'NavDestinationInfo',
  'NavDestinationMode', 'NavDestinationTransition', 'NavExtender', 'NavPathInfo',
  'NavPathStack', 'NavRouteMode', 'NavigationAnimatedTransition', 'NavigationCommonTitle',
  'NavigationCustomTitle', 'NavigationDividerStyle', 'NavigationInfo',
  'NavigationInterception', 'NavigationMenuItem', 'NavigationMenuOptions',
  'NavigationMode', 'NavigationOperation', 'NavigationOptions',
  'NavigationSystemTransitionType', 'NavigationTitleMode', 'NavigationTitleOptions',
  'NavigationToolbarOptions', 'NavigationTransitionProxy', 'NavigationType',
  'NestedScrollInfo', 'NestedScrollMode', 'NestedScrollOptions', 'NestedScrollOptionsExt',
  'Node', 'NodeController', 'NonCurrentDayStyle', 'Nullable', 'ObscuredReasons',
  'OffscreenCanvas', 'OffscreenCanvasRenderingContext2D', 'Offset', 'OffsetOptions',
  'OffsetResult', 'OnAdsBlockedCallback', 'OnAlertEvent', 'OnAlphabetIndexerPopupSelectCallback',
  'OnAlphabetIndexerRequestPopupDataCallback', 'OnAlphabetIndexerSelectCallback',
  'OnAudioStateChangedEvent', 'OnBeforeUnloadEvent', 'OnCheckboxChangeCallback',
  'OnCheckboxGroupChangeCallback', 'OnClientAuthenticationEvent', 'OnConfirmEvent',
  'OnConsoleEvent', 'OnContentScrollCallback', 'OnContextMenuHideCallback',
  'OnContextMenuShowEvent', 'OnDataResubmittedEvent', 'OnDidChangeCallback',
  'OnDownloadStartEvent', 'OnErrorReceiveEvent', 'OnFaviconReceivedEvent',
  'OnFirstContentfulPaintEvent', 'OnFirstMeaningfulPaintCallback', 'OnFoldStatusChangeCallback',
  'OnFoldStatusChangeInfo', 'OnFullScreenEnterCallback', 'OnGeolocationShowEvent',
  'OnHoverStatusChangeCallback', 'OnHttpAuthRequestEvent', 'OnHttpErrorReceiveEvent',
  'OnIntelligentTrackingPreventionCallback', 'OnInterceptRequestEvent',
  'OnLargestContentfulPaintCallback', 'OnLinearIndicatorChangeCallback', 'OnLoadInterceptEvent',
  'OnMoveHandler', 'OnNativeEmbedVisibilityChangeCallback', 'OnNativeLoadCallback',
  'OnNavigationEntryCommittedCallback', 'OnOverScrollEvent', 'OnOverrideUrlLoadingCallback',
  'OnPageBeginEvent', 'OnPageEndEvent', 'OnPageVisibleEvent', 'OnPasteCallback',
  'OnPermissionRequestEvent', 'OnProgressChangeEvent', 'OnPromptEvent',
  'OnRefreshAccessedHistoryEvent', 'OnRenderExitedEvent',
  'OnRenderProcessNotRespondingCallback', 'OnRenderProcessRespondingCallback',
  'OnResourceLoadEvent', 'OnSafeBrowsingCheckResultCallback', 'OnScaleChangeEvent',
  'OnScreenCaptureRequestEvent', 'OnScrollCallback', 'OnScrollEdgeCallback', 'OnScrollEvent',
  'OnScrollFrameBeginCallback', 'OnScrollFrameBeginHandlerResult',
  'OnScrollVisibleContentChangeCallback', 'OnSearchResultReceiveEvent',
  'OnShowFileSelectorEvent', 'OnSslErrorEventCallback', 'OnSslErrorEventReceiveEvent',
  'OnSubmitCallback', 'OnSwiperAnimationEndCallback', 'OnSwiperAnimationStartCallback',
  'OnSwiperGestureSwipeCallback', 'OnTabsAnimationEndCallback', 'OnTabsAnimationStartCallback',
  'OnTabsContentWillChangeCallback', 'OnTabsGestureSwipeCallback',
  'OnTextSelectionChangeCallback', 'OnTitleReceiveEvent', 'OnTouchIconUrlReceivedEvent',
  'OnViewportFitChangedCallback', 'OnWillScrollCallback', 'OnWindowNewEvent', 'Once',
  'OptionWidthMode', 'Optional', 'OutlineOptions', 'OutlineRadiuses', 'OutlineStyle',
  'OverScrollMode', 'OverlayOffset', 'OverlayOptions', 'PX', 'Padding', 'PageFlipMode',
  'PageTransitionCallback', 'PageTransitionEnter', 'PageTransitionExit',
  'PageTransitionOptions', 'PanDirection', 'PanGesture', 'PanGestureEvent',
  'PanGestureHandler', 'PanGestureHandlerOptions', 'PanGestureOptions', 'PanGestureParams',
  'PanRecognizer', 'PanelHeight', 'PanelMode', 'PanelType', 'ParagraphStyle',
  'ParagraphStyleInterface', 'ParticleAnnulusRegion', 'ParticleColorOptions',
  'ParticleColorPropertyOptions', 'ParticleColorPropertyUpdaterConfigs',
  'ParticleColorUpdaterOptions', 'ParticleConfigs', 'ParticleEmitterShape',
  'ParticleOptions', 'ParticlePropertyAnimation', 'ParticlePropertyOptions',
  'ParticlePropertyUpdaterConfigs', 'ParticleTuple', 'ParticleType', 'ParticleUpdater',
  'ParticleUpdaterOptions', 'Particles', 'PasswordIcon', 'PasteButtonOnClickResult',
  'PasteButtonOptions', 'PasteDescription', 'PasteEvent', 'PasteEventCallback',
  'PasteIconStyle', 'Path2D', 'PathOptions', 'PathShape', 'PathShapeOptions',
  'PatternLockChallengeResult', 'PatternLockController', 'Percentage',
  'PerfMonitorActionType', 'PerfMonitorSourceType', 'PermissionRequest',
  'PersistPropsOptions', 'PersistentStorage', 'PickerBackgroundStyle',
  'PickerDialogButtonStyle', 'PickerTextStyle', 'PinchGesture', 'PinchGestureEvent',
  'PinchGestureHandler', 'PinchGestureHandlerOptions', 'PinchGestureParams',
  'PinchRecognizer', 'PixelMap', 'PixelMapMock', 'PixelRoundCalcPolicy', 'PixelRoundMode',
  'PixelRoundPolicy', 'PixelStretchEffectOptions', 'PlaceholderStyle', 'Placement',
  'PlayMode', 'PlaybackInfo', 'PlaybackSpeed', 'PluginComponentOptions',
  'PluginComponentTemplate', 'PluginErrorCallback', 'PluginErrorData', 'Point',
  'PointLightStyle', 'PointParticleParameters', 'PointerStyle', 'PolygonOptions',
  'PolylineOptions', 'PopInfo', 'PopupBorderLinearGradient', 'PopupCommonOptions',
  'PopupMaskType', 'PopupMessageOptions', 'PopupOptions', 'PopupStateChangeParam',
  'Position', 'PositionT', 'PositionWithAffinity', 'PosterOptions', 'PreDragStatus',
  'PreparedInfo', 'Preview', 'PreviewConfiguration', 'PreviewMenuOptions', 'PreviewParams',
  'PreviewText', 'Profiler', 'ProgressConfiguration', 'ProgressMask', 'ProgressOptions',
  'ProgressStatus', 'ProgressStyle', 'ProgressStyleMap', 'ProgressStyleOptions',
  'ProgressType', 'Prop', 'ProtectedResourceType', 'Provide', 'ProvideOptions',
  'Provider', 'PulseSymbolEffect', 'QuickReplaceSymbolEffect', 'RRect',
  'RadialGradientOptions', 'RadioConfiguration', 'RadioIndicatorType', 'RadioOptions',
  'RadioStyle', 'RatingConfiguration', 'RatingOptions', 'RawFileDescriptor',
  'ReceiveCallback', 'RectHeightStyle', 'RectOptions', 'RectResult', 'RectShape',
  'RectShapeOptions', 'RectWidthStyle', 'Rectangle', 'RefreshOptions', 'RefreshStatus',
  'RelateType', 'RenderExitReason', 'RenderFit', 'RenderMode',
  'RenderProcessNotRespondingData', 'RenderProcessNotRespondingReason',
  'RenderingContextSettings', 'RepeatItem', 'RepeatMode', 'ReplaceSymbolEffect',
  'ResizableOptions', 'ResolutionQuality', 'Resource', 'ResourceColor',
  'ResourceImageAttachmentOptions', 'ResourceStr', 'ResponseType', 'RestrictedWorker',
  'ReuseOptions', 'RichEditorBaseController', 'RichEditorBuilderSpanOptions',
  'RichEditorChangeValue', 'RichEditorController', 'RichEditorDeleteDirection',
  'RichEditorDeleteValue', 'RichEditorGesture', 'RichEditorImageSpan',
  'RichEditorImageSpanOptions', 'RichEditorImageSpanResult', 'RichEditorImageSpanStyle',
  'RichEditorImageSpanStyleResult', 'RichEditorInsertValue', 'RichEditorLayoutStyle',
  'RichEditorOptions', 'RichEditorParagraphResult', 'RichEditorParagraphStyle',
  'RichEditorParagraphStyleOptions', 'RichEditorRange', 'RichEditorResponseType',
  'RichEditorSelection', 'RichEditorSpan', 'RichEditorSpanPosition',
  'RichEditorSpanStyleOptions', 'RichEditorSpanType', 'RichEditorStyledStringController',
  'RichEditorStyledStringOptions', 'RichEditorSymbolSpanOptions',
  'RichEditorSymbolSpanStyle', 'RichEditorSymbolSpanStyleResult', 'RichEditorTextSpan',
  'RichEditorTextSpanOptions', 'RichEditorTextSpanResult', 'RichEditorTextStyle',
  'RichEditorTextStyleResult', 'RichEditorUpdateImageSpanStyleOptions',
  'RichEditorUpdateSymbolSpanStyleOptions', 'RichEditorUpdateTextSpanStyleOptions',
  'RichEditorUrlStyle', 'RingStyleOptions', 'Root', 'RootSceneSession', 'RotateOptions',
  'RotationGesture', 'RotationGestureEvent', 'RotationGestureHandler',
  'RotationGestureHandlerOptions', 'RotationGestureParams', 'RotationRecognizer',
  'RoundRectShapeOptions', 'RoundedRectOptions', 'RouteInfo', 'RouteMapConfig',
  'RouteType', 'RouterPageInfo', 'RowOptions', 'RowOptionsV2', 'RuntimeType',
  'SafeAreaEdge', 'SafeAreaType', 'SaveButtonOnClickResult', 'SaveButtonOptions',
  'SaveDescription', 'SaveIconStyle', 'ScaleOptions', 'ScaleRingStyleOptions',
  'ScaleSymbolEffect', 'ScanEffectOptions', 'Scene', 'SceneOptions', 'ScreenCaptureConfig',
  'ScreenCaptureHandler', 'ScriptItem', 'ScrollAlign', 'ScrollAnimationOptions',
  'ScrollBarDirection', 'ScrollBarMargin', 'ScrollBarOptions', 'ScrollDirection',
  'ScrollEdgeOptions', 'ScrollMotion', 'ScrollOnScrollCallback', 'ScrollOnWillScrollCallback',
  'ScrollOptions', 'ScrollPageOptions', 'ScrollResult', 'ScrollSizeMode',
  'ScrollSnapAlign', 'ScrollSnapOptions', 'ScrollSource', 'ScrollState',
  'ScrollToIndexOptions', 'ScrollableBarModeOptions', 'ScrollableCommonMethod',
  'ScrollableTargetInfo', 'Scroller', 'SearchButtonOptions', 'SearchController',
  'SearchOptions', 'SearchSubmitCallback', 'SearchType', 'SectionOptions',
  'SecurityComponentLayoutDirection', 'SecurityComponentMethod', 'SeekMode',
  'SelectOption', 'SelectStatus', 'SelectedMode', 'SelectionMenuOptions',
  'SelectionMenuOptionsExt', 'SelectionOptions', 'Serializer', 'ShadowOptions',
  'ShadowStyle', 'ShadowType', 'ShapeSize', 'SharedTransitionEffectType', 'SheetDismiss',
  'SheetInfo', 'SheetKeyboardAvoidMode', 'SheetMode', 'SheetOptions', 'SheetSize',
  'SheetTitleOptions', 'SheetType', 'ShouldBuiltInRecognizerParallelWithCallback',
  'SideBarContainerType', 'SideBarPosition', 'Size', 'SizeChangeCallback', 'SizeOptions',
  'SizeResult', 'SizeT', 'SizeType', 'SlideEffect', 'SlideRange', 'SliderBlockStyle',
  'SliderBlockType', 'SliderChangeMode', 'SliderConfiguration', 'SliderCustomContentOptions',
  'SliderInteraction', 'SliderOptions', 'SliderPrefixOptions', 'SliderShowStepOptions',
  'SliderStepItemAccessibility', 'SliderStyle', 'SliderSuffixOptions',
  'SliderTriggerChangeCallback', 'SnapshotOptions', 'SourceTool', 'SourceType',
  'SpanStyle', 'SpringBackAction', 'SpringMotion', 'SpringProp', 'SslError',
  'SslErrorEvent', 'SslErrorHandler', 'StackOptions', 'StarStyleOptions', 'State',
  'StateStyles', 'Sticky', 'StickyStyle', 'Storage', 'StyleOptions', 'StyledString',
  'StyledStringChangeValue', 'StyledStringChangedListener', 'StyledStringController',
  'StyledStringKey', 'StyledStringValue', 'Styles', 'SubMenuExpandingMode',
  'SubTabBarStyle', 'SubmitCallback', 'SubmitEvent', 'SubscribaleAbstract',
  'SubscribedAbstractProperty', 'Summary', 'SuperscriptStyle', 'SurfaceRect',
  'SurfaceRotationOptions', 'SweepGradientOptions', 'SwipeActionItem', 'SwipeActionOptions',
  'SwipeActionState', 'SwipeDirection', 'SwipeEdgeEffect', 'SwipeGesture',
  'SwipeGestureEvent', 'SwipeGestureHandler', 'SwipeGestureHandlerOptions',
  'SwipeGestureParams', 'SwipeRecognizer', 'Swiper', 'SwiperAnimationEvent',
  'SwiperAnimationMode', 'SwiperAutoFill', 'SwiperContentAnimatedTransition',
  'SwiperContentTransitionProxy', 'SwiperContentWillScrollResult', 'SwiperController',
  'SwiperDisplayMode', 'SwiperNestedScrollMode', 'SwitchStyle', 'SymbolEffect',
  'SymbolEffectStrategy', 'SymbolGlyphModifier', 'SymbolRenderingStrategy',
  'SyncedPropertyOneWay', 'SyncedPropertyTwoWay', 'SystemAdaptiveOptions',
  'SystemBarStyle', 'SystemOps', 'TabBarIconStyle', 'TabBarOptions', 'TabBarSymbol',
  'TabContentAnimatedTransition', 'TabContentTransitionProxy', 'TabsAnimationEvent',
  'TabsCacheMode', 'TabsController', 'TabsCustomContentTransitionCallback',
  'TabsOptions', 'Tag', 'TapGesture', 'TapGestureEvent', 'TapGestureHandler',
  'TapGestureHandlerOptions', 'TapGestureParameters', 'TapGestureParams',
  'TapRecognizer', 'TemplateOptions', 'TerminationInfo', 'Test', 'TextAlign',
  'TextAreaController', 'TextAreaOptions', 'TextAreaSubmitCallback', 'TextAreaType',
  'TextBackgroundStyle', 'TextBaseController', 'TextBox', 'TextCascadePickerRangeContent',
  'TextCase', 'TextChangeOptions', 'TextChangeReason', 'TextClockConfiguration',
  'TextClockController', 'TextClockOptions', 'TextContentControllerBase',
  'TextContentControllerOptions', 'TextContentStyle', 'TextController',
  'TextDataDetectorConfig', 'TextDataDetectorType', 'TextDecorationOptions',
  'TextDecorationStyle', 'TextDecorationType', 'TextDeleteDirection',
  'TextEditControllerEx', 'TextHeightAdaptivePolicy', 'TextLayoutOptions',
  'TextInputController', 'TextInputOptions', 'TextInputStyle', 'TextMarqueeOptions',
  'TextMenuItem', 'TextMenuItemId', 'TextMenuOptions', 'TextMenuShowMode', 'TextMetrics',
  'TextModifier', 'TextOptions', 'TextOverflow', 'TextOverflowOptions',
  'TextPickerDialog', 'TextPickerDialogOptions', 'TextPickerOptions',
  'TextPickerRangeContent', 'TextPickerResult', 'TextPickerTextStyle', 'TextRange',
  'TextResponseType', 'TextSelectableMode', 'TextShadowStyle', 'TextSpanType',
  'TextStyle', 'TextTimerConfiguration', 'TextTimerController', 'TextTimerOptions',
  'Theme', 'ThemeColorMode', 'ThreatType', 'TimePickerDialog', 'TimePickerDialogOptions',
  'TimePickerFormat', 'TimePickerOptions', 'TimePickerResult', 'TipsOptions',
  'TitleHeight', 'TodayStyle', 'ToggleConfiguration', 'ToggleOptions', 'ToggleType',
  'ToolBarItemInterface', 'ToolBarItemOptions', 'ToolBarItemPlacement', 'ToolbarItem',
  'ToolbarItemStatus', 'TouchEvent', 'TouchObject', 'TouchPoint', 'TouchResult',
  'TouchTestInfo', 'TouchTestStrategy', 'TouchType', 'Trace', 'Track', 'TransitionEdge',
  'TransitionEffect', 'TransitionEffects', 'TransitionFinishCallback',
  'TransitionHierarchyStrategy', 'TransitionOptions', 'TransitionType',
  'TranslateOptions', 'UICommonEvent', 'UIContext', 'UIExtensionOptions',
  'UIExtensionProxy', 'UIGestureEvent', 'UnderlineColor', 'UnifiedData',
  'UniformDataType', 'UrlStyle', 'UserDataSpan', 'VMContext', 'VP', 'VelocityOptions',
  'VerticalAlign', 'VideoController', 'VideoOptions', 'View', 'ViewportFit',
  'ViewportRect', 'VirtualScrollOptions', 'Visibility', 'VisibleAreaChangeCallback',
  'VisibleAreaEventOptions', 'VisibleListContentInfo', 'VisualEffect', 'VoiceButtonOptions',
  'VoidCallback', 'Want', 'Watch', 'WaterFlowLayoutMode', 'WaterFlowOptions',
  'WaterFlowSections', 'WebCaptureMode', 'WebContextMenuParam', 'WebContextMenuResult',
  'WebController', 'WebCookie', 'WebDarkMode', 'WebElementType', 'WebHeader',
  'WebKeyboardAvoidMode', 'WebKeyboardCallback', 'WebKeyboardCallbackInfo',
  'WebKeyboardController', 'WebKeyboardOptions', 'WebLayoutMode', 'WebMediaOptions',
  'WebNavigationType', 'WebOptions', 'WebResourceError', 'WebResourceRequest',
  'WebResourceResponse', 'WebResponseType', 'WebviewController', 'Week', 'WeekStyle',
  'WidthBreakpoint', 'WindowAnimationTarget', 'WindowModeFollowStrategy',
  'WindowStatusType', 'WithThemeOptions', 'WordBreak', 'WorkStateStyle', 'WrappedBuilder',
  'XComponentController', 'XComponentOptions', 'XComponentType', 'animateTo',
  'animateToImmediately', 'cursorControl', 'focusControl', 'fp2px', 'getContext',
  'getInspectorNodeById', 'getInspectorNodes', 'lpx2px', 'postCardAction', 'px2fp',
  'px2lpx', 'px2vp', 'setAppBgColor', 'sharedTransitionOptions', 'vp2px'
]);

const decoratorsWhiteList = [
  'State', 'Prop', 'Link', 'Observed', 'Track', 'ObjectLink', 'StorageProp', 'StorageLink',
  'LocalStorageProp', 'LocalStorageLink', 'Provide', 'Consume', 'Watch',
  'Local', 'Param', 'Once', 'Event', 'Provider', 'Consumer', 'Monitor', 'Computed', '@ObservedV2', 'Trace',
  'Builder', 'BuildParam', 'Styles', 'Extend', 'AnimatableExtend', 'Type', 'Require',
  'Reusable', 'ReusableV2', 'Entry', 'Component', 'ComponentV2', 'CustomDialog'
];

const whiteFileList = [
  '@ohos.app.ability.continueManager',
  '@ohos.app.ability.InsightIntentDecorator',
  '@ohos.app.ability.UIExtensionContentSession',
  '@ohos.distributedsched.proxyChannelManager',
  '@ohos.graphics.displaySync',
  '@ohos.graphics.drawing', 
  '@ohos.graphics.text',
  '@ohos.i18n',
  '@ohos.inputMethodEngine',
  '@ohos.userIAM.userAuth',
  '@ohos.web.webview',
  'LiveFormExtensionContext',
  'Scene',
  'SceneResources',
  'UIAbilityContext',
];

const apiDir = [
  'ability', 'advertising', 'app', 'application', 'arkui', 'bundle', 'bundleManager', 'commonEvent',
  'continuation', 'data', 'global', 'graphics3d', 'multimedia', 'notification', 'security', 'tag',
  'wantAgent'
];

const apiInternalDir = [
  '@internal/full'
];

export {
  apiDir,
  apiInternalDir,
  whiteList,
  decoratorsWhiteList,
  whiteFileList,
};
